CC = gcc
CFLAGS = -Wall 
$(info ************ Wykonano zadanie 2 ************)

static:
	$(CC) $(CFLAGS) client.c -o client -lrt
	$(CC) $(CFLAGS) server.c -o server -lrt

clean:
	rm -rf client server raport.txt