CC = gcc
CFLAGS = -Wall 
$(info ************ Wykonano zadanie 3 ************)

static:
	$(CC) $(CFLAGS) sender.c -o sender
	$(CC) $(CFLAGS) catcher.c -o catcher
# raport: static
# 	./main > raport.txt
# clean:
# 	rm -rf main raport.txt