CC = gcc
CFLAGS = -Wall 
$(info ************ Wykonano zadanie 1 ************)

static:
	$(CC) $(CFLAGS) simulation.c -o simulation
	$(CC) $(CFLAGS) client.c -o client
	$(CC) $(CFLAGS) hairdresser.c -o hairdresser
clean:
	rm -rf client simulation hairdresser raport.txt